language: go

services:
  - docker

dist: trusty

go:
  - "1.11.x"
  - "1.10.x"
  - "tip"

env:
  global:
    - IMAGINARY_VERSION=${TRAVIS_TAG:-"dev"}
    - DCMD="docker run --rm -i -v ${TRAVIS_BUILD_DIR}:/go/src/github/h2non/imaginary -w /go/src/github/h2non/imaginary h2non/imaginary:build"
  matrix:
    - LIBVIPS=8.7.2
    - LIBVIPS=master

matrix:
  allow_failures:
    - env: LIBVIPS=master
    - go: "tip"

before_install:
  - true

install:
  - true

script:
  - echo "go test -v -race -covermode=atomic" | ${DCMD}
