language: go

services:
  - docker

dist: trusty

go:
  - "1.11.x"
  - "1.10.x"
  - "tip"

env:
  global:
    - IMAGINARY_VERSION="${TRAVIS_TAG:-dev}"
    - DCMD="docker run --rm -i -v ${TRAVIS_BUILD_DIR}:/go/src/github/h2non/imaginary -w /go/src/github/h2non/imaginary h2non/imaginary:build"
  matrix:
    - LIBVIPS=8.7.2
    - LIBVIPS=master

matrix:
  allow_failures:
    - env: LIBVIPS=master
    - go: "tip"

before_install:
  - docker pull h2non/imaginary:build || true

install:
  - true

script:
  - echo "go test -v -race -covermode=atomic" | ${DCMD}
  - docker build --pull --cache-from h2non/imaginary:build --build-arg IMAGINARY_VERSION="${IMAGINARY_VERSION#v}" --tag h2non/imaginary:${IMAGINARY_VERSION} .

before_deploy:
#  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
#  provider: script
#  script:
#    - docker tag h2non/imaginary:${IMAGINARY_VERSION} latest
#    - docker push h2non/imaginary:${IMAGINARY_VERSION}
#    - docker push h2non/imaginary:latest
#  on:
#    condition: "${TRAVIS_TAG} =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
